#!/usr/bin/env ruby

require 'gtk3'

application_root_path = File.expand_path(__dir__)
Dir[File.join(application_root_path, '**', '*.rb')].each { |file| require file }

app = Comix::Application.new

puts app.run